### ISSUE TITLE
a demo ?

### ISSUE THREAD

**Issue by xiaolongyuan** [AndroidKnife/RxBus#1]

**Comment by hwangjr** [comment]
no, you can read [README.md](https://github.com/AndroidKnife/RxBus/blob/master/README.md) for more detail, if you have any issue, welcome to new issue or pull request~

**Comment by xiaolongyuan** [comment]
Thank you for your reply.
'Otto' has been deprecated.
This project can use it in a production environment? It's stable?

**Comment by hwangjr** [comment]
First of all, i have use it in my project. :)
For [RxJava](https://github.com/ReactiveX/RxJava), i have this suggestions:
1. if your app use [RxJava](https://github.com/ReactiveX/RxJava), you can consider this repo, the code is very simplify. just add the annotation to use rxjava for event bus.
2. if your app don't use rxjava, then you can consider this repo or other even library like [greenrobot/EventBus](https://github.com/greenrobot/EventBus).
3. if you think this repo is too heavy, you can try [RxBus/RxBusOlder.java](https://github.com/AndroidKnife/RxBus/blob/master/rxbus%2Fsrc%2Fmain%2Fjava%2Fcom%2Fhwangjr%2Frxbus%2FRxBusOlder.java), this is the easiest way to use rxjava to transform your event.

**Comment by xiaolongyuan** [comment]
Thanks. @hwangjr
