### ISSUE TITLE
Replace EventBus

### ISSUE THREAD

**Issue by carmas123** [AndroidKnife/RxBus#10]
Hi, I want to replace EventuBus with RxBus in my application...but when I start to work with it I found initial problem for me. In EventBus I've a method `isRegistered` to check if an object is registered. Where is it into RxBus?

**Comment by hwangjr** [comment]
`isRegistered` is not provided now, you use this function in what condition? Maybe you can post some code.

**Comment by hwangjr** [comment]
Still here ?   or i will close this issue~
