### ISSUE TITLE
how to use @Produce？

### ISSUE THREAD

**Issue by doulala1986** [AndroidKnife/RxBus#11]
hi，
 The anonotation style RxBus is very cool, I can understard how to use @Subsribe after read your sample and doc。 could you tell me，how to use @Produce,  add a sample for it is better~

thanks!

**Comment by hwangjr** [comment]
[RxBus/MouseMam.java at master · AndroidKnife/RxBus](https://github.com/AndroidKnife/RxBus/blob/master/app/src/main/java/com/hwangjr/rxbus/app/MouseMam.java)

Checkout this~

**Comment by doulala1986** [comment]
I had download this demo yesterday，I found when the object is registered，the tell() function will execute. but i still can not understard **what is @Produce use for **。I think it is the  call back of register event？

**Comment by hwangjr** [comment]
When subscribing to events it is often desired to also fetch the current known value for specific events (e.g., current location, active user, etc.). `Produce` provide an immediate callback to any subscribers upon their registration.

**Comment by doulala1986** [comment]
thank you！
