### ISSUE TITLE
readme  setp2  compile fail 

### ISSUE THREAD

**Issue by yanglinglong1** [AndroidKnife/RxBus#15]
`public static final class RxBus {
    private static Bus sBus;

    public static synchronized get() {
        if (sBus == null) {
            sBus = new Bus();
        }
        return sBus;
    }
}`

forget return Bus 

`public static final class RxBus {
    private static Bus sBus;

    public static synchronized Bus get() {
        if (sBus == null) {
            sBus = new Bus();
        }
        return sBus;
    }
}`

**Comment by hwangjr** [comment]
Opps, i will fix it. and for more details, you can check out [RxBus.java](https://github.com/AndroidKnife/RxBus/blob/master/rxbus/src/main/java/com/hwangjr/rxbus/RxBus.java)
