### ISSUE TITLE
Minimum SDK Issue

### ISSUE THREAD

**Issue by chanlapp** [AndroidKnife/RxBus#16]
Is there any reason for migrating the minimum sdk to 15?

**Comment by hwangjr** [comment]
I'm not going to make a release just for a minimum sdk support. You can use 1.0.5-SNAPSHOT for now.

details [support minimum sdk to 9](https://github.com/AndroidKnife/RxBus/commit/8db587f059fa7d997a31a52387529ec88b04d4a1)

[Index of /repositories/snapshots/com/hwangjr/rxbus/rxbus](https://oss.sonatype.org/content/repositories/snapshots/com/hwangjr/rxbus/rxbus/)
