### ISSUE TITLE
消息为原始类型时候，无法正常订阅到

### ISSUE THREAD

**Issue by baidusoso** [AndroidKnife/RxBus#19]
如bus.post(1) 在subscribe(int msg)无法订阅到

**Comment by hwangjr** [comment]
try this:
```
subscribe(Integer xxx);
```

**Comment by hwangjr** [comment]
问题解决了吗？如果已经解决，可以close issue～

**Comment by baidusoso** [comment]
subscribe(Integer xxx);是可以避免，但不过友好。
我的本义是建议你在Bus类的 getClassesFor(Class<?> concreteClass)增加对原始类型的支持，或者增加注解表明不能用原始类型。

**Comment by hwangjr** [comment]
增加注解表明不能使用原始类型？   这个如何增加，有什么建议。欢迎pull 过来～

**Comment by LycInSzu** [comment]
如果是原始类型就抛个自定义的异常？

**Comment by hwangjr** [comment]
目前如果是interface会抛异常

**Comment by ViTess** [comment]
主要是基本类型的封包问题，建议加上基本类型的TYPE判断，比如`Integer.TYPE`
