### ISSUE TITLE
我被你的demo搞懵了，看了使用文档，有些疑问，特来询问。

### ISSUE THREAD

**Issue by leguang** [AndroidKnife/RxBus#22]
@hwangjr 
很抱歉的打扰你了，因为我实在是看不懂你的demo
首先是文档里描述的代码
`    @Subscribe
    public void eat(String food) {
        // purpose
    }

    @Subscribe(
        thread = EventThread.IO,
        tags = {
            @Tag(BusAction.EAT_MORE)
        }
    )
    public void eatMore(List<String> foods) {
        // purpose
    }

    @Produce
    public String produceFood() {
        return "This is bread!";
    }

    @Produce(
        thread = EventThread.IO,
        tags = {
            @Tag(BusAction.EAT_MORE)
        }
    )
    public List<String> produceMoreFood() {
        return Arrays.asList("This is breads!");
    }`

我们在使用Otto或者EvenBus的时候，是post一个，然后在要用的类中就注册和反注册，然后用一个注解标记一个函数，这个函数就会自动调用。我看你这个库很类似，所以本来打算用的，但是看到你的这段代码，我就糊涂了，请问是不是每次我要在用的类中注册和反注册了之后，在希望被调用的函数上面都要写
` @Subscribe
    public void eat(String food) {
        // purpose
    }

    @Subscribe(
        thread = EventThread.IO,
        tags = {
            @Tag(BusAction.EAT_MORE)
        }
    )
    public void eatMore(List<String> foods) {
        // purpose
    }`
我的意思是先想表达：是不是必须得有两个@Subscribe + @Subscribe(
        thread = EventThread.IO,
        tags = {
            @Tag(BusAction.EAT_MORE)
        }
    )

您是想表达什么意思？
是两者都行？还是两者都必须得写了才可以？
还有你的demo，犹豫没看懂，能不能稍微提示一下用法。
我就想发送一个消息，在另一个类中能接收到，从这种最简单的用法开始就好。你的demo里由于看不出来你哪里生产哪里消费了。所以才来这里提问的。
期待你的解答^_^

**Comment by hwangjr** [comment]
如果你使用过`otto`的话，那么使用方式和`otto`一样。这里想表达的是，`subscribe`注解如果默认的情况下是如何使用，以及在指定分发的`thread`及`tag`的情况下是如何使用的。

**Comment by ArtisanM** [comment]
tag注解是用来做什么的？

**Comment by hwangjr** [comment]
tag，可以给事件进行分类，事件的类型。string。你可以不用设置，默认。

**Comment by hwangjr** [comment]
如果没有其他疑问，可以关闭issue？

**Comment by leguang** [comment]
@hwangjr 
已经没有疑问了，谢谢你的解答，您可以关闭这个issue了^_^
