### ISSUE TITLE
minsdkVersion

### ISSUE THREAD

**Issue by Chaoxyc** [AndroidKnife/RxBus#23]
通过依赖下载下来，提示我sdkversion不能小于15，
com.hwangjr.rxbus\rxbus\1.0.4\AndroidManifest.xml中，
<uses-sdk
        android:minSdkVersion="15"
        android:targetSdkVersion="24" />
demo中最低不是9么

**Comment by hwangjr** [comment]
#16 , i will release a new version soon.

**Comment by Chaoxyc** [comment]
thank you

**Comment by hwangjr** [comment]
already release new version!
