### ISSUE TITLE
Provide some more examples

### ISSUE THREAD

**Issue by ShivamDev31** [AndroidKnife/RxBus#24]
Hi can you provide some more examples please?

Like if I want to switch to 1 fragment to another from a button click in Fragment1 I want to go to Fragment2, so I've used activity for replacement logic. 

In Activity I've 
@Subscribe(tags = {@Tag(RxConstants.EventType.SCREEN_SWITCH_EVENT)})

In Activity I'm adding Fragment1 by 
@Produce(tags = {@Tag(RxConstants.EventType.SCREEN_SWITCH_EVENT)})
    private Screen getRegisterScreen() {
        return Screen.REGISTER;
    }

Now in Fragment1 on the click of a Button I want to replace Fragment1 with Fragment2. 

So in Fragment2 I'm doing something like this:

@Produce(tags = {@Tag(RxConstants.EventType.SCREEN_SWITCH_EVENT)})
    private VehicleActivity.Screen getListingScreen() {
        return VehicleActivity.Screen.VEHICLE_LISTING;
    }

But when it will be executed? As I want it to execute on the click of a button.

So can you please guide me with the same?

**Comment by ShivamDev31** [comment]
I got it, .post() is there for this.
Can you please add the same in Readme.md and your sample app.

**Comment by hwangjr** [comment]
you can find the usage/example here: [app](https://github.com/AndroidKnife/RxBus/tree/master/app)

**Comment by ShivamDev31** [comment]
Have already gone through the app and it doesn't cover post() and your ReadMe covers the @Annotations only. Just a suggestion to provide a more detailed sample.

**Comment by hwangjr** [comment]
Mmm, I have add this to [RxBus/README.md at master · AndroidKnife/RxBus](https://github.com/AndroidKnife/RxBus/blob/master/README.md).

It also used in demo, here: [RxBus/MouseMam.java at master · AndroidKnife/RxBus](https://github.com/AndroidKnife/RxBus/blob/master/app/src/main/java/com/hwangjr/rxbus/app/MouseMam.java)

**Comment by ShivamDev31** [comment]
I thing I'm not clear with, 
Do I need to register/unregister in all the classes where I'm using @subscribe, @produce .post or only where I use  @subscribe, @produce .

Also I've an activity and I'm doing  
RxBus.get().post(BusAction.EAT_MORE, this);
and there there is a dialog somewhere where I'm doing

@Subscribe(tags = {@Tag(BusAction.EAT_MORE)})
subscribeMe(Object obj) {
    // the code is never reaching here. So not able to get this obj
}

I've done register and unregister in both activity and dialog.

So anyway to diagnose this issue by any logging or maybe I'm doing something wrong?

**Comment by hwangjr** [comment]
1. Only where you use the annotation( @subscribe and @produce), you should register/unregister the class.
2. You post the activity, but while you want to receive an object, so it can't receive the post. you should make sure that you post the Cat, and you also want to receive the Cat (not Mouse).

**Comment by ShivamDev31** [comment]
Sorry that example was copied from your post only from different places, have updated the example.

So here is my scenario : 
Activity A --> Posts an Obj... Then Activity B--> Open a Dialog in in Activity B and tried to @Subscribe the Obj in the Dialog. But not getting anything...

**Comment by hwangjr** [comment]
Only the subscribed object can receive the post object, so please make sure that you have subscribe the object and then post the data.

**Comment by ShivamDev31** [comment]
I checked out your sample as well as ReadMe but did not understand it properly, so have created a demo project where I tried to mock my real scenario as much as possible. https://github.com/ShivamDev31/RxBusDemo

Maybe you can tell me now what I'm doing wrong.

**Comment by hwangjr** [comment]
If you have fix the issue, please close this issue.
