### ISSUE TITLE
请问@Produce数据刷新

### ISSUE THREAD

**Issue by tianxiao875** [AndroidKnife/RxBus#25]
@Produce 返回的String值该改变后。。怎么刷新Subscribe接受的数据哇？otto 有bus.register(); 
但是我找不到刷新Subscribe的方法。。。

**Comment by tianxiao875** [comment]
我的意思就是，，有没有不如我只用某个方法后。所有的Subscribe会重新执行一边、

**Comment by hwangjr** [comment]
RxBus.getInstance().post(Constants.EventType.TAG_STORY, this);

Maybe this can solve your problem : [RxBus/MouseMam.java at master · AndroidKnife/RxBus](https://github.com/AndroidKnife/RxBus/blob/master/app/src/main/java/com/hwangjr/rxbus/app/MouseMam.java)

**Comment by hwangjr** [comment]
If you have fix the problem, you can close this issue?
