### ISSUE TITLE
Registering the listener in base class doesn`t work

### ISSUE THREAD

**Issue by teddybee** [AndroidKnife/RxBus#29]
I have a some activities, I have made a Base class for them where I put the registration into the OnCreate() method, unregister the listener in the OnDestroy().
The Subscribe method is also in the Base class.
Unfortunately the messages newer arrived for the subscribers. If I move the Subscribe methods into the child class, it is working good.
Is there something I have missed, or is it a bug in the RxBus?

**Comment by hwangjr** [comment]
Ref  #13

**Comment by teddybee** [comment]
Thank you for the help!
