### ISSUE TITLE
Add Samples

### ISSUE THREAD

**Issue by hwangjr** [AndroidKnife/RxBus#3]
Add usage to sample, include subscribe and producer etc..

**Comment by xiaolongyuan** [comment]
+1

**Comment by hwangjr** [comment]
Add samples on [app folder](https://github.com/AndroidKnife/RxBus/tree/master/app).

**Comment by xiaolongyuan** [comment]
good

**Comment by hwangjr** [comment]
Release [1.0.3](https://github.com/AndroidKnife/RxBus/releases/tag/1.0.3)
