### ISSUE TITLE
Check is the event is registered

### ISSUE THREAD

**Issue by ShivamDev31** [AndroidKnife/RxBus#30]
Hi,

Is there any method like isRegistered or something to check if the event is registered or not?

When I'm opening an Activity which is in foreground there I'm getting exception : 

Caused by: java.lang.IllegalArgumentException: Producer method for type [EventType selected_event && class Vehicle] found on type class DiscoveryActivity, but already registered by type class SpotDiscoveryActivity.

While I checked the code in Bus class line 185 you have put in check and throwing this exception.
So instead of throwing an exception you can skip the registration part and the flow will continue.
Else you can provide an isRegistered method to check if the event is already not registered only then it will subscribe to it.

As of now the app is crashing.

**Comment by ShivamDev31** [comment]
Changed this : 
if (previousProducer != null) {
                Log.e(TAG, "Producer method for type " + type
                        + " found on type " + producer.getTarget().getClass()
                        + ", but already registered by type " + previousProducer.getTarget().getClass() + ".");
                return;
            }

Its working fine now(but don't know it might create problems later on) but I really think you should have an isRegistered method

**Comment by MMooreGitHub** [comment]
Same issue here. an isRegistered flag would be great to have.

**Comment by hwangjr** [comment]
i will add this function in next milestone.
