### ISSUE TITLE
请问怎么解决不能识别List集合？

### ISSUE THREAD

**Issue by xubuhang** [AndroidKnife/RxBus#34]
Activity.getSelectedFields(java.util.List) has @Subscribe annotation on interface java.util.List which is an interface.  Subscription must be on a concrete class type.

<img width="1215" alt="qq20161115-0 2x" src="https://cloud.githubusercontent.com/assets/4189632/20301636/114ee400-ab5f-11e6-85e8-511f38a95c5f.png">

**Comment by hwangjr** [comment]
Ref #33  #29  #13

**Comment by xubuhang** [comment]
@hwangjr 没有效果，请帮我看看
<img width="1176" alt="qq20161117-0 2x" src="https://cloud.githubusercontent.com/assets/4189632/20373673/476bf58c-acae-11e6-9093-d3b2fe4de650.png">

**Comment by hwangjr** [comment]
你将注册的方法的参数List 修改为真正的类型试试

**Comment by xubuhang** [comment]
@hwangjr 我不理解什么是真正的类型？我只想传递类型是Field的list， 真正的类型难道是单个field还是基本类型String？我现在只想传递一个list有办法吗？

**Comment by reStarting** [comment]
list是接口, 你要把list改成ArraryList, LinkedList 这种可以直接new出来的类型

**Comment by xubuhang** [comment]
@reStarting 按照你的方法终于好了，真心感谢🙏🙏🙏
