### ISSUE TITLE
关于RxBus

### ISSUE THREAD

**Issue by xturbofan** [AndroidKnife/RxBus#35]
看了你的这个项目的源码，发现和EventBus的原理类似，但是看到这篇文章http://www.jianshu.com/p/ca090f6e2fe2/# ，想问下这个项目和文章里的Rxbus有何异同点啊？还有就是这个项目好像并没有用到Rxjava(除了在Bus类中有用到Action1).

**Comment by hwangjr** [comment]
如果你阅读过源码，就会发现里面有个 [RxBusOlder.java](https://github.com/AndroidKnife/RxBus/blob/master/rxbus/src/main/java/com/hwangjr/rxbus/RxBusOlder.java)，这里就是旧版本的实现。为什么会有这个库，是因为如果单纯的使用RxBusOlder，也是可以实现的，但是对于我而言不是很方便，无法通过注解等其他方式简单实现，降低使用门槛。
这个库只是我将核心部分，使用rxjava来进行dispatch，在此基础上增加了注解方式来使用。
以上。

**Comment by xturbofan** [comment]
@hwangjr thanks!好吧，确实没注意RxBusOlder这个类，看了下发现确实是和文章里的介绍基本上一样的。
