### ISSUE TITLE
先发送消息，后注册，这种有办法收到么？

### ISSUE THREAD

**Issue by cikichen** [AndroidKnife/RxBus#36]
我可能启动app的时候就发送了消息，但是页面要后续切换过去才注册，这样可以处理么？

`Sticky事件`

**Comment by hwangjr** [comment]
可以看下@Produce注解，能否解决你的问题。

**Comment by cikichen** [comment]
@hwangjr 测试了，不行呢

**Comment by hwangjr** [comment]
你的应用场景能否描述下？

**Comment by cikichen** [comment]
@hwangjr 比如我的app启动的时候有一个后台service也同时启动做了一些操作，这个service的操作可能根据具体场景执行时间有快有慢，时间是无法把控的，执行完成后会把结果post到某一个页面刷新，而这个页面刚启动的时候是没有初始化的，用户有可能在service执行的任何时间段切换到需要接受数据的页面，现在的情况是无法接收到这种数据。

**Comment by hwangjr** [comment]
1 在Service中使用Produce注解，返回service操作的结果，如果还未则返回null
2 在Service操作结果出来之后，使用post方法发送此结果
3 在页面中注册此消息接收，如果有消息则进行展示，如果是null，则提示正在计算

不知道酱紫逻辑是否可以解决你的问题。

**Comment by cikichen** [comment]
@hwangjr 现在貌似从service post出去的事件UI接受不到

**Comment by hwangjr** [comment]
能否贴出关键代码方便我排查？或者创建一个demo我fork然后调试？

**Comment by cikichen** [comment]
@hwangjr 问题确认，RxBus无法支持跨进程通信

**Comment by sjcao** [comment]
跨进程通信怎么解决

**Comment by hwangjr** [comment]
android上，一般AIDL，也有很多其他方式，具体根据业务场景，不过不在此库的讨论范围。
