### ISSUE TITLE
more examples needed

### ISSUE THREAD

**Issue by jjhesk** [AndroidKnife/RxBus#38]
question. when im doing a io thread with a tag called "network_io" .
i put into this to execute the thread

```java

object_cc  = pp_item;
RxBus.get().post("network_io", pp_item);

//when the io thread is complete
@Subscribe(thread = EventThread.IO, tags = {@Tag("network_io")})

```

what is the best way to notify the mainthread when the job is complete?
do i just do another post call to the mainthread like this?
```java
  @Subscribe(thread = EventThread.MAIN_THREAD, tags = {@Tag("network_io")})
```

**Comment by jjhesk** [comment]
at the end got an error. 
```
ID: 6423
                                                              java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
```

**Comment by hwangjr** [comment]
I found the key error word `realm`, this error log shows that you can't pass the Realm Objects from other thread, so you should pass this from the source thread.
I think you can do the computing from other thread, then use RxBus to post the result to the main thread.

**Comment by jjhesk** [comment]
so after all is my proposal thread plan is feasible?

**Comment by hwangjr** [comment]
For realm(from error log), you can not use realm object in other thread.
Also, you can send an flag to io thread to start a job, and send result to main thread while the job is finished. RxBus can satisfied this situation. But why can't you just use RxJava to do this job in a straight way? like : 
```
        Observable.create((Subscriber<? super Object> subscriber) -> {
            // do something background
            subscriber.onNext(result);
        }).observeOn(AndroidSchedulers.mainThread())
                .subscribeOn(Schedulers.io())
                .subscribe(result -> {
                    // do something in main thread
                }, throwable -> {
                    // do something while error occurs
                });
```

**Comment by jdestremps** [comment]
I am looking at the cat/mouse/mousemom example, and all it has is a mail icon, and you click on it, and it just displays some text.  It registers the mousemom and catMom.birth() but then I don't see how anything is actually used or observed anywhere.  And there is a lot of dead code that never gets accessed.  Would be nice to have some examples that actually exercised helped how this all works.  This doesn't really help, and it seems like it's the only thing the app does:

                Snackbar.make(view, "Birth a mouse and squeak ! " + mouse, Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();

**Comment by hwangjr** [comment]
@jdestremps, have you ever use any eventbus like greenrobot/EventBus or Square/otto?
The only thing is register, and post the event, subscribe will catch the event.
Just like produce a mouse, the cat will catch the mouse, that's all. you also can checkout the log from console.

**Comment by jdestremps** [comment]
Yeah, sorry, I did not have error logging turned on.  I changed all Timber.e to Timber.d and now see the output for the posts in CatMom.  I also removed the tags and the tag subscription, and that also works, so I'm good for now.  Thanks!

**Comment by jdestremps** [comment]
Quick question.  If I unregister and something posts, and then I re-register when I come back into the activity, will it pick up the event?

**Comment by hwangjr** [comment]
NO, you can checkout the DEAD EVENT or producer annotation. 
This is not this topic question, if you have any other question, welcome to commit an issue~
@jjhesk Have your issue got fixed? Maybe it's time to close this issue?

**Comment by jjhesk** [comment]
i have fixed the issue by far, but i want to know more how to efficiently implement a io call of worked call that will finally callback to the mainthread. thanks

**Comment by hwangjr** [comment]
I don't really know about "efficiently implement a io call or a worker call that will finally callback to the main thread.". you think now rxbus can't callback to main thread efficiently?

**Comment by jjhesk** [comment]
Im not sure for now. because i havent done any statistical analysis. It was just my plain guess.
