### ISSUE TITLE
可否改进成编译时生成代码？

### ISSUE THREAD

**Issue by ViTess** [AndroidKnife/RxBus#41]
作者您好，非常感谢您开源此项目，我在其中学习到了很多，也模仿写了一个基于反射的RxBus。

不过，我在其中发现一些问题。一个是参数类型的问题，如基本类型还可以判断其封包，但是一些数据类型（如`List`、`Map`、`Set`等）和包含泛型之类的参数判断较为复杂，不好处理；二是反射调用在android下的效率确实不高。

因此我开始尝试改进，用编译时自动生成绑定(Tag -> Subject)的代理.class方式。目前自己已实现了大致方向上的生成类文件和绑定操作，但还是遇到一些困难：
1. 以Tag和调用方法的参数作为key，对应不同的Subject，在参数判断上不好操作，而且不同参数能对应一个tag的感觉指向不明确，因此我觉得一个Tag对应一种方法参数比较合适，实现难度也降低些。
2. Subject传递参数时，是否符合其参数类型这一点依然比较难判断。最近在看`ButterKnife`的代码，觉得或许可以通过自定义Lint，在用户使用`RxBus.post()`时检查参数类型。

以上是我的部分想法，希望能与作者交流交流 (•̀ᴗ•́)و ̑̑

**Comment by hwangjr** [comment]
感谢您的尝试，你说的是一个需要提高的方向，但是由于我时间上一直腾不出来，所以就一直没有处理这个事情。如果感兴趣，可以将代码提交到git上一起讨论。

**Comment by a483210** [comment]
@ViTess 你看下我写的[RxBus](https://github.com/a483210/RxBus)对你有没有帮助
