### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by asstea** [AndroidKnife/RxBus#44]
可以提供粘性事件传递，类似eventbus的Sticky事件。

**Comment by Gorcyn** [comment]
I think you should translate your request to English to let more people understand you and help you.

**Comment by asstea** [comment]
I'm sorry, I have already solved the problem



644276142@qq.com
 
发件人： Ludovic Garcia
发送时间： 2017-02-20 21:41
收件人： AndroidKnife/RxBus
抄送： asstea; Author
主题： Re: [AndroidKnife/RxBus] 建议 (#44)
I think you should translate your request to English to let more people understand you and help you.

**Comment by chxchen** [comment]
@asstea 请问你怎么解决这个粘性事件的问题? How did you do to solve the problem?

**Comment by asstea** [comment]
@Produce 使用这个注解。

**Comment by chxchen** [comment]
@asstea 这个注解是对象生成时发送事件。你是指利用produce通知"粘性事件源"重新发送一次消息?
