### ISSUE TITLE
监听问题

### ISSUE THREAD

**Issue by allen218** [AndroidKnife/RxBus#45]

**Comment by allen218** [comment]
作者你好，非常感谢你提供这么好的组件，我们开发小组使用你的组件可以非常方便的完成一些交互。目前我们遇到了一个问题，就是在父类里注册了监听(@subscriber)后，没有办法回调到，必须要写在子类才能收到监听，请问这个问题能解决不？

**Comment by fanturbo** [comment]
#49

**Comment by hwangjr** [comment]
resolved~
