### ISSUE TITLE
关于在Fragment使用上的疑问？

### ISSUE THREAD

**Issue by JeremyLam1** [AndroidKnife/RxBus#47]
您好，我的界面是一个MainActivity里有多个Fragment（1,2,3,4），我现在想在fragment1发出事件，在fragment2里消费事件。那我使用的话，我的rxbus是只需要声明在register/unregister在MainActivity上，然后暴露方法给各个fragment调用呢？还是在每个Fragment都声明一个rxbus，然后register/unregister？

望解答，谢谢！

**Comment by zhangzhigang168** [comment]
换到 fragment中注册呢？
