### ISSUE TITLE
Rxbus silent failure InvocationTargetException - beta version

### ISSUE THREAD

**Issue by rachitananda** [AndroidKnife/RxBus#50]
The Rxbus very frequently not able to dispatch event, although I get value but it silently fails. Only when I debug I get invocationTargetException at SubscriberEvent class -->initObservable().

Is there any work around around for this ? 
I'm using com.hwangjr.rxbus:rxbus:2.0.0-beta for RXjava2 from https://github.com/AndroidKnife/RxBus/tree/2.x

Thanks

**Comment by hwangjr** [comment]
Can you show me some snippets or logs?

**Comment by hwangjr** [comment]
This happens here, do you unregister from the bus and still sending events ?


```

                    @Override
                    public void accept(Object event) {
                        try {
                            if (valid) {
                                handleEvent(event);
                            }
                        } catch (InvocationTargetException e) {
                            throwRuntimeException("Could not dispatch event: " + event.getClass() + " to subscriber " + SubscriberEvent.this, e);
                        }
                    }
```
