### ISSUE TITLE
未register的时候，调用unregister会抛异常

### ISSUE THREAD

**Issue by ArtisanM** [AndroidKnife/RxBus#51]
为啥得抛异常？我有时候为了性能考虑，在activity创建时判断一些必要条件，如果不满足就直接finish，这种情况下是不会register Rxbus的，但是我在onDestory时统一unregister，然后Rxbus就抛异常了。

难道这种情况我还得记个flag？总感觉在这种情况下直接抛异常的设计很不好。我也不可能try catch，这样是有性能开销的

**Comment by hwangjr** [comment]
feel free to reopen the issue if you still have problems.
