### ISSUE TITLE
Android MVP项目的P层里网络访问结束后执行RxBus的post方法，闪退。

### ISSUE THREAD

**Issue by xubuhang** [AndroidKnife/RxBus#54]
Android MVP项目的P层里网络访问结束后执行RxBus的post方法，闪退。
![6857a184-760f-4184-86b4-3647c0d4d75e](https://cloud.githubusercontent.com/assets/4189632/25038195/f5c7b1e8-212f-11e7-94f9-97524662f523.png)
在V层里执行RxBus的post方法就可以。
请问这是怎么回事？

**Comment by hwangjr** [comment]
any messages?

**Comment by hwangjr** [comment]
feel free to reopen the issue if you still have problems.
