### ISSUE TITLE
关于demo

### ISSUE THREAD

**Issue by KobeBryant824** [AndroidKnife/RxBus#55]
感觉你写的demo太抽象化了，是否多添加几个简单的页面跳转；
虽然用到了rxjava的事件分发，但整体感觉还是跟eventbus、otto类似

**Comment by hwangjr** [comment]
其实代码很简单，你可以看下，就只是核心的分发做了修改。

demo的话，目前应该不会继续优化，如果你有兴趣可以围绕tom来做个小小的story。

**Comment by hwangjr** [comment]
如果对此issue有其他疑问，请重新开启并留言
