### ISSUE TITLE
是否支持重新订阅

### ISSUE THREAD

**Issue by KobeBryant824** [AndroidKnife/RxBus#64]
@Subscribe事件回调中，如果代码存在异常，能否不抛运行时异常，帮忙捕获并自动订阅呢，我看EventBus有处理。

**Comment by hwangjr** [comment]
这类我是建议在回调方法里自行处理，如果`rxbus`将此异常捕获，外面是无法针对此异常进行处理。而且，从职责上来说，`rxbus`不对订阅方法的异常进行处理，换句话说，`rxbus`也不知道如何处理，只能忽略。

**Comment by KobeBryant824** [comment]
evevtbus没有抛运行时异常但有打印错误堆栈信息，而且自动订阅，我怕万一上线不可避免在回调里偶尔会出错，后面就接不到信息了

**Comment by hwangjr** [comment]
如果回调里出错了，应用正常应该会崩溃。另一方面，如果回调里考虑的逻辑周全点，是否应该捕获下异常？可以考虑下。
