### ISSUE TITLE
Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by Mao-x-w** [AndroidKnife/RxBus#67]
here is my code:
@Subscribe(tags = {@Tag(ImagePickerActivity.RX_EVENT_IMAGE)},thread = EventThread.MAIN_THREAD)
	public void onPicker(String[] images) {
              ........
        }

in onPicker method,I use AsyncTask to upload image throw error:Can't create handler inside thread that has not called Looper.prepare().  I use the most of solution on net,but not worked.can you help me ,thank you

**Comment by hwangjr** [comment]
post your asynctask code?

you also can run subscribe in other thread, and just post the image to server, then callback to main thread.

**Comment by Mao-x-w** [comment]
OK,I solve it,thank you very much.

**Comment by hwangjr** [comment]
it's okay.
