### ISSUE TITLE
support  25.4.0  ????!! --->>26.0.0-alpha1

### ISSUE THREAD

**Issue by NW0LC** [AndroidKnife/RxBus#68]

**Comment by hwangjr** [comment]
i just use the lasted stable version, you can change to 26.0.0-alpha1, it should be ok.

and this libraries only use for examples.

**Comment by NW0LC** [comment]
我自己替换好麻烦。。support好像没有23.4.0这个版本吧？

**Comment by hwangjr** [comment]
do it yourself and you will get food and clothing you need ample food and clothing through self reliance.
