### ISSUE TITLE
Proguard问题

### ISSUE THREAD

**Issue by sw926** [AndroidKnife/RxBus#69]
出现了
```
Caused by java.lang.NoSuchFieldException: MAIN_THREAD
```
添加了规则
```
-keep class com.hwangjr.rxbus.thread.EventThread { *; }
```
后解决，我是用的Kotlin，不知道在Java里面会不会出现这个问题

**Comment by hwangjr** [comment]
#7   you should check you have already use this tips.

**Comment by sw926** [comment]
It fixed my problem, I found RxBus use "consumerProguardFiles" in "build.gradle",so I didn't add rules in my proguard file.

**Comment by hwangjr** [comment]
yep, in fact i have already add proguard rules in library.

if you solved this issue, close it?

**Comment by sw926** [comment]
最终还得得添加
```
-keep class com.hwangjr.rxbus.thread.EventThread { *; }
```
library里面的规则能保证编译通过，但是我遇到的问题是在运行时出现的，可能是因为使用Kotlin的问题吧。

**Comment by sw926** [comment]
我先close了，添加了规则后没有出现过问题，Rxbus非常好用，谢谢 @hwangjr

**Comment by kraghu** [comment]
we arw facing this issue. Your proguard files are not helpful . the conversation here is in non english . any help ? or work arounD ?

**Comment by sw926** [comment]
I fix my problem by add 
```
-keep class com.hwangjr.rxbus.thread.EventThread { *; }
```
It now works well
