### ISSUE TITLE
一个Activity创建了多个相同的Fragment，多次添加数据

### ISSUE THREAD

**Issue by 965310001** [AndroidKnife/RxBus#70]
Fragment我使用的是懒加载  Fragment中的listview会多次添加相同的数据
特别是在TabLayout+Fragment的时候特别明显

**Comment by hwangjr** [comment]
这跟 rxbus 有什么关系。。

**Comment by 965310001** [comment]
一个Activity中有两个或者多个相同的BaseFragment的时候会，它是怎么接受的,它是怎么区分是哪一个Fragment的接受呢

**Comment by 965310001** [comment]
例如：我有两个Activity，都用了rxbus注册，只要Activity的TAG是相同的，两个Activity是不是都会接受rxbus发送的数据呢

**Comment by hwangjr** [comment]
这个跟你的具体业务场景有关，跟 `rxbus` 没关系。 如果你想区分，那你得思考为何要分开，要以哪个来 分开，然后在业务逻辑上进行区分。

**Comment by hwangjr** [comment]
如果仍有问题，可以重新打开 issue。
