### ISSUE TITLE
有个建议

### ISSUE THREAD

**Issue by vihuela** [AndroidKnife/RxBus#72]
一直用eventBus的原因是，支持基类订阅，子类复写，可接收这个特性非常重要啊
[反射不能获取父类方法？](https://github.com/AndroidKnife/RxBus/blob/master/rxbus/src/main/java/com/hwangjr/rxbus/finder/AnnotatedFinder.java#L55)，我调试了一下，确实啊

**Comment by hwangjr** [comment]
这个我反倒觉得还好，因为这个也是有方法解决的。而如果基于基类，要么做反射，要么动态生成代码。反射的话，如果多层，我觉得不是一个好的方式。动态生成代码，目前 eventbus 是有做，或者你可以尝试下，然后推个 request 过来。
