### ISSUE TITLE
 compile 'com.hwangjr.rxbus:rxbus:1.0.6' can not work 

### ISSUE THREAD

**Issue by wangweijun120** [AndroidKnife/RxBus#73]
Error:Failed to resolve: annotationProcessor
<a href="openFile:D:/Android/WSY/app/build.gradle">Open File</a>

Error:Failed to resolve: com.android.support:support-annotations:25.4.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:D:/Android/WSY/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

![image](https://user-images.githubusercontent.com/22536326/28751857-d5a7dc08-7544-11e7-9c7e-7d23b6a19601.png)

**Comment by hwangjr** [comment]
you should update your annotations version

**Comment by wangweijun120** [comment]
How can i solve this problem? I have google it but can not find a proper solution.

**Comment by hwangjr** [comment]
you can click : Install Repository and sync project

**Comment by wangweijun120** [comment]
I did so many times, but my android studio did not have any reaction,,is it meet some problem?
 My android studio version is 2.3.3

**Comment by hwangjr** [comment]
you can checkout the setting in Android Studio -> Preference -> Android SDK, and choose SDK Tools tab, then update your dependencies like Android Support Repository etc...

**Comment by wangweijun120** [comment]
![image](https://user-images.githubusercontent.com/22536326/28807901-ca9fa1e4-76aa-11e7-92d6-bb26d3f10229.png)
I have do this ,but it still can not work

**Comment by hwangjr** [comment]
Still can't work?

**Comment by wangweijun120** [comment]
Well, I do not know what to do, so I can only give up using this library，，

**Comment by gongtingshisi** [comment]
ok,this is because that it depends on android annotation 25.4.0,while you have no it locally(search Library/Android/sdk/extras/android/m2repository/) and in remote repository configured in top build.gradle.Maybe this link is you dish:[https://github.com/mikepenz/MaterialDrawer/issues/1915](url)
