### ISSUE TITLE
似乎与butterknife存在一些冲突  如何解决？

### ISSUE THREAD

**Issue by chxchen** [AndroidKnife/RxBus#76]
在butterknife存在的情况，添加RxBus的依赖之后就会出现这个Gradle错误。
请问怎么解决？
（1.没有添加RxBus依赖时，Gradle能正常Sync
2.添加RxBus之后，Sync出现这个错误
3.删除RxBus依赖后正常）
Error:Could not find com.android.support:support-annotations:25.4.0.
Required by:
    project :app > com.jakewharton:butterknife:8.8.1
    project :app > com.jakewharton:butterknife:8.8.1 > com.jakewharton:butterknife-annotations:8.8.1

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>

**Comment by chxchen** [comment]
SDK已经更新过了，另一个项目没有butterknife，添加RxBus依赖能正常工作

**Comment by hwangjr** [comment]
add google repository, try this :  

```
allprojects {
    repositories {
        . . . 
        google()
        . . .
    }
}
```

**Comment by tx123456** [comment]
我也遇到了这个问题，添加google()好像也不起作用

Error:(19, 0) Gradle DSL method not found: 'google()'
Possible causes:<ul><li>The project 'ziyuanhui' may be using a version of the Android Gradle plug-in that does not contain the method (e.g. 'testCompile' was added in 1.1.0).
<a href="fixGradleElements">Upgrade plugin to version 3.0.0-beta3 and sync project</a></li><li>The project 'ziyuanhui' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>

**Comment by hwangjr** [comment]
@tx123456  那后面你如何解决的？   这个应该是依赖库问题，不是代码问题。那你有试过这个：

```
allprojects {
    repositories {
        ...
        maven {
            url "https://maven.google.com"
        }
        ...
    }
}
```

**Comment by tx123456** [comment]
用这种方法可以导入，谢谢

**Comment by hwangjr** [comment]
ok, i will close it now.
