### ISSUE TITLE
how to make sticky event

### ISSUE THREAD

**Issue by AndwareSsj** [AndroidKnife/RxBus#8]

**Comment by hwangjr** [comment]
sticky event is not support now~

**Comment by hwangjr** [comment]
you can try annotation: [Produce.java](https://github.com/AndroidKnife/RxBus/blob/master/rxbus/src/main/java/com/hwangjr/rxbus/annotation/Produce.java)

sample: [RxBus/MouseMam.java at master · AndroidKnife/RxBus](https://github.com/AndroidKnife/RxBus/blob/master/app/src/main/java/com/hwangjr/rxbus/app/MouseMam.java)

**Comment by linheimx** [comment]
+1

**Comment by jp1017** [comment]
求支持啊，可以看下这个 :smile: 

http://www.jianshu.com/p/71ab00a2677b

**Comment by hwangjr** [comment]
这个不是Produce就可以实现？
