### ISSUE TITLE
能否增加是否已经注册的判断？

### ISSUE THREAD

**Issue by AndSync** [AndroidKnife/RxBus#80]
像 eventbus那样 EventBus.getDefault().isRegistered(this)

**Comment by hwangjr** [comment]
已经添加，但是不推荐使用。   `hasRegistered`

**Comment by AndSync** [comment]
@hwangjr  没找到啊 我用的2.0.0版本

**Comment by hwangjr** [comment]
我会在 2.0 上添加下，但是我有个疑惑，这个场景其实应该不常见才对。因为这个方法的实现不是很好的方式。

你可以分享下你的使用场景吗？

**Comment by AndSync** [comment]
@hwangjr 比如新闻评论输入框 我们把评论及输入框等抽取到一个自定义View里面 这里面有一个收藏按钮 需要跳转登录页面 登录完成之后还要继续执行收藏操作 因此采用 rxbus 或者eventbus来做 当然 这个其实是不能回收的 因为这里面没有生命周期  

还有些情况比如多个页面要公用一个adapter 可能也会在adapter里面这样操作 如果要回调到 Activity 或者fragment里面去处理  就要写很多遍重复的逻辑。 

我也觉得不太好但是不知道是否有更好的办法？

**Comment by hwangjr** [comment]
比如新闻评论输入框 我们把评论及输入框等抽取到一个自定义View里面 这里面有一个收藏按钮 需要跳转登录页面 登录完成之后还要继续执行收藏操作 因此采用 rxbus 或者eventbus来做 当然 这个其实是不能回收的 因为这里面没有生命周期

**Comment by AndSync** [comment]
@hwangjr 跳转的时候点的比较快了 就会报异常 说已经注册过了

**Comment by hwangjr** [comment]
你是单例？ 不然应该是不一样的实例不是？

**Comment by AndSync** [comment]
@hwangjr 我明白你说的意思，比如在Activity里面注册的话 连续跳转到该Activity每次都是一个新的实例
但是现在的应用场景是 在该自定义View里面进行注册的，每次由该View跳转到新的页面都进行注册，注册的代码是在这个自定义View里面的，依然是这个View的实例啊
下面代码是我自己加的判断

····
private void dealWithCollection() {
        if (!UserHelper.isLogin()) {
            if(!hasRegister){
                RxBus.get().register(this);
                hasRegister =true;
            }
            LoginEvent.getInstance().setType(LoginEvent.Type.REQUEST_TYPE_COMMENT);
            Intent intent = new Intent(context, LoginActivity.class);
            context.startActivity(intent);
        } else {
            doCollect();
        }
    }
····

**Comment by hwangjr** [comment]
view 的话，你在 `attach` 的时候去注册， `detach` 的时候注销，不是吗？

**Comment by AndSync** [comment]
不是的 我是在点击事件的时候注册的
attach  detach  怎么用能写详细一下吗？

另外 在Adapter里面注册的话如何回收呢？

**Comment by hwangjr** [comment]
我感觉你使用错了，方向错误，怎么可能会有在 `adapter` 里面注册的需求？

`attach` 具体你可以看下 `view` 的生命周期。

**Comment by hwangjr** [comment]
#30  close this.
