### ISSUE TITLE
低概率挂

### ISSUE THREAD

**Issue by huangyong0301** [AndroidKnife/RxBus#81]
大神江湖救急：
概率性挂掉
希望能帮忙解决一下

使用了com.hwangjr.rxbus:rxbus:2.0.0后 有时线上用户会出现crash

public class RxBus {
    private static Bus sBus;

    public RxBus() {
    }

    public static synchronized Bus get() {
        if(sBus == null) {
            sBus = new Bus(ThreadEnforcer.ANY);
        }

        return sBus;
    }
}

post地方

RxBus.get().post(RXTags.UNREAD_COUNT_ADD, "");   //增加一条未读消息

接收的地方
@Subscribe(tags = {@Tag(RXTags.UNREAD_COUNT_ADD)})
public void setUnreadAdd(String no) {
    //查询未读个数
    cureFunApi.qryUnReadCount(MyApplication.getInstance().getUserId());
}

![tim 20170911193610](https://user-images.githubusercontent.com/12829384/30272718-7148c64a-9728-11e7-9161-3d0922747355.png)

**Comment by hwangjr** [comment]
check 下 `com.curefun.tools.e.H(string)` 方法的 mapping，看是具体什么类什么方法。看着是你代码里面有使用到反射？  或者最简单处理方式就是：

```
@subscribe(tags = {@tag(RXTags.UNREAD_COUNT_ADD)})
public void setUnreadAdd(String no) {
    try {
        //查询未读个数
        cureFunApi.qryUnReadCount(MyApplication.getInstance().getUserId());
    catch(Exception e) {
        // exception
    }
}
```

**Comment by hwangjr** [comment]
feel free to reopen the issue if you still have problems.
