### ISSUE TITLE
传递list对象时数据丢失

### ISSUE THREAD

**Issue by ArtisanM** [AndroidKnife/RxBus#83]
<img width="766" alt="2017-10-20 3 21 52" src="https://user-images.githubusercontent.com/13694153/31809545-d62bbec2-b53d-11e7-8998-e95199a15001.png">
<img width="750" alt="2017-10-20 3 22 16" src="https://user-images.githubusercontent.com/13694153/31809551-dbe731e8-b53d-11e7-94a0-039fdf9ec61f.png">

如图，传递前list里有两条数据，subscriber接收到的就变成0条数据了。

event对象结构如下

```

    public final int code;
    public ArrayList<ImageInfo> data;


    public VerifyEvent(int code) {
        this.code = code;
    }

    public VerifyEvent(int code, ArrayList<ImageInfo> data) {
        this.code = code;
        this.data = data;
    }
```

**Comment by hwangjr** [comment]
？

**Comment by ArtisanM** [comment]
发现是自己代码的问题。抱歉
