### ISSUE TITLE
How do you upload this library with third-party libraries?

### ISSUE THREAD

**Issue by pokk** [AndroidKnife/RxBus#85]
I'm sorry about my question isn't related with this project.

I just wonder how do you do it with Jake Wharton's timber library. Could you tell me about that?
Thank you very much!

**Comment by hwangjr** [comment]
```
compile ('com.hwangjr.rxbus:rxbus:1.0.6') {
    exclude group: 'com.jakewharton.timber', module: 'timber'
}
```

Like this? this is just exclude the timber library, because i just use the library for log in RxBus.

**Comment by pokk** [comment]
For example, I'd like to upload my library with `rxJava`.
But I couldn't find `rxJava` in my project after I've uploaded my library with `rxJava`.

There is not `rxJava` library without I do like this. :((
```
compile ('io.reactivex.rxjava2:rxjava:2.1.6') {
    exclude group: 'io.reactivex.rxjava2', module: 'rxjava'
}
```

Do you know which part is wrong?

**Comment by hwangjr** [comment]
this just add the compile library . maybe you can find this answer in stack.

**Comment by pokk** [comment]
I recognized why import my library without external libraries.

I used the `implementation "xxxx"`, if I use `compile "xxxx"`. The `xxxx` will import together with my library.
