### ISSUE TITLE
How can I use it in Kotlin?

### ISSUE THREAD

**Issue by WellerV** [AndroidKnife/RxBus#88]
In Kotlin, annotations is not support. When I use @Subscribe, it show errors.

**Comment by WellerV** [comment]
I had subscribe it like this,
`    @Subscribe(
            thread = EventThread.MAIN_THREAD,
            tags = arrayOf(Tag(BusTag.VideoPlay.PROGRESS_CHANGED))
    )
    fun onVideoProgressChanged(progress: Int) {

    }
`
I post event in sub thread,
`
          RxBus.get().post(BusTag.VideoPlay.PROGRESS_CHANGED,
                            (100 * 87L / 100L).toInt())
`
I debug the code,find the Int in Kotlin is not same as the Integer in java, so 
`
 Set<SubscriberEvent> wrappers = getSubscribersForEventType(new EventType(tag, clazz));
`
wrappers can't be found.It dispatch a DeadEvent.

**Comment by bluemix** [comment]
i got the same problem here

**Comment by hwangjr** [comment]
Yes, the type here is not compatible.

**Comment by Blizzard-liu** [comment]
@bluemix @WellerV 发送的事件不能是基本类型就ok了  改成String类型

**Comment by WellerV** [comment]
@Blizzard-liu 自己修改源码解决了，不可能所有int类型的都改成String，这个还是很影响效率的。

**Comment by hwangjr** [comment]
https://github.com/AndroidKnife/RxBus/pull/95

**Comment by kssilvoza** [comment]
Hello, when will the version with the Kotlin fix be released?

**Comment by hwangjr** [comment]
@kssilvoza  Already released for 2.0.1 version.

**Comment by mozhou5555** [comment]
@hwangjr 2.0.1 没有合入#95的代码
![image](https://user-images.githubusercontent.com/7950923/104007964-b9b4ec00-51e3-11eb-8a33-b4373c190522.png)

**Comment by hwangjr** [comment]
@mozhou5555  already release 2.0.2 & 3.0.0
