### ISSUE TITLE
关于粘性事件与@produce的问题,how to handle with sticky event by '@produce'

### ISSUE THREAD

**Issue by chxchen** [AndroidKnife/RxBus#90]
@hwangjr 您好!我查看了大部分的关于@produce的issue
我现在需要处理类似粘性事件的问题,看到issue里,您推荐使用@produce,
如果我理解没错,@produce应该是在对象调用register方法之后调用的吧,用来发送事件的.
现在我的场景需求如下:
A组件创建后会启动B组件并且会发送一个B需要关心的事件;
B组件启动时间是未知的(事件发送与B组件启动时间无确切先后);
A组件随时可能会销毁。
如果我在B组件中使用@produce,来通知A组件"B组件已经准备好"，然后A再次发送该事件来实现的话。可能B组件@produce的时候A组件已经销毁了.

**Comment by hwangjr** [comment]
你在 A 组件中创建一个 `produce`，然后启动 B 组件的时候，自然就会收到 A 组件自动 `produce` 的一个事件了。而且 A 销毁的话，B 肯定也相对应销毁，不影响。
