### ISSUE TITLE
是否可以升级下rxjava和rxandroid的版本，现在的版本太久了，新版本很多类都没了

### ISSUE THREAD

**Issue by tyl210110** [AndroidKnife/RxBus#96]
是否可以升级下rxjava和rxandroid的版本，现在的版本太久了，新版本很多类都没了

**Comment by xushanning** [comment]
附议，现在貌似都是rx2了，很多项目引用不了这个。。

**Comment by hwangjr** [comment]
我看了版本还好？  rx2 的话，用 rx2 的分支就好了。

**Comment by hwangjr** [comment]
https://github.com/AndroidKnife/RxBus/tree/2.x
