### ISSUE TITLE
发送一个post 接收到2次

### ISSUE THREAD

**Issue by yuzhongrong** [AndroidKnife/RxBus#99]
发送一个post 接收到2次
<img width="370" alt="22222" src="https://user-images.githubusercontent.com/7382234/57638129-b1a44380-75df-11e9-99ce-a40156576a46.png">

**Comment by hwangjr** [comment]
有可能注册了两次？  给些代码看下。

**Comment by yuzhongrong** [comment]
我在baseactivity  oncreate()时候注册 在ondestroy（）时候销毁

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/57825147-3c4b9500-77d0-11e9-9588-1956f3c7a7ee.png)
![image](https://user-images.githubusercontent.com/7382234/57825176-57b6a000-77d0-11e9-897a-97652552c6fc.png)
![image](https://user-images.githubusercontent.com/7382234/57825209-77e65f00-77d0-11e9-9dc5-8f143d43d712.png)

**Comment by hwangjr** [comment]
#13  基类参考这种实现。

**Comment by yuzhongrong** [comment]
我基类是固定的不可能按照你这样命名

**Comment by yuzhongrong** [comment]
我看你代码 是去重复 订阅的 做了过滤的啊

**Comment by yuzhongrong** [comment]
![image](https://user-images.githubusercontent.com/7382234/57941120-9fd4e000-7900-11e9-932a-1b220c0f30f5.png)

**Comment by hwangjr** [comment]
查下发消息发了几次，是否多次执行。

**Comment by hwangjr** [comment]
如果还有问题可以重开下。
